### ISSUE TITLE
[EPIC] UI Baseline

### ISSUE THREAD

**Issue by leonardtng** [leonardtng/cryptoscapes#1]
**Baseline**
- [x] Base theme
- [x] Drawer navigation
- [x] Page Layout template

**List of Tasks (Complete in order)**
The tasks below can be completed in order (or not) to complete this feature.

1. [x] [TASK: Theme Toggle](https://github.com/leonardtng/cryptoscapes/issues/30)
2. [x] [TASK: Responsive UI](https://github.com/leonardtng/cryptoscapes/issues/31)
3. [x] [TASK: Back to Top Floating Button](https://github.com/leonardtng/cryptoscapes/issues/25)
4. [x] [TASK: Progressive Web App](https://github.com/leonardtng/cryptoscapes/issues/32)
