### ISSUE TITLE
[EPIC] Coins Page

### ISSUE THREAD

**Issue by leonardtng** [leonardtng/cryptoscapes#16]
**Epic Details**
This feature will allow the viewing of the entire list of support cryptocurrency coins on Coingecko

**Describe the solution you'd like**
User can view a list of coins and sort them by coin market cap and volume. Also able to load more coins after scrolling to the end of the list. Upon clicking a coin item, brings them to a detailed coin page.

**List of Tasks (Complete in order)**
The tasks below can be completed in order (or not) to complete this feature.

1. [x] [TASK: Coin List Table](https://github.com/leonardtng/cryptoscapes/issues/17)
2. [x] [TASK: Coin Details Page](https://github.com/leonardtng/cryptoscapes/issues/18)
3. [x] [TASK: Link to Coin Details Page](https://github.com/leonardtng/cryptoscapes/issues/19)
4. [x] [TASK: Coins Search Bar](https://github.com/leonardtng/cryptoscapes/issues/20)

**Additional context**
