### ISSUE TITLE
[EPIC] Overview Page

### ISSUE THREAD

**Issue by leonardtng** [leonardtng/cryptoscapes#2]
**Epic Details**
This feature will add the main overview analytics page where the user will be able to see various data visualisations pertaining to cryptocurrency coins

**Describe the solution you'd like**
Charts and analytics on coins today Mainly, a Top coin chart, dominance chart, ETH gas fees, top institution holders and some global data.

**List of Tasks (Complete in order)**
The tasks below can be completed in order (or not) to complete this feature.

1. [x] [TASK: Top Coins Card](https://github.com/leonardtng/cryptoscapes/issues/3)
2. [x] [TASK: Top 2 Coin Dominance Chart](https://github.com/leonardtng/cryptoscapes/issues/6)
3. [x] [TASK: ETH Gas Fees Card](https://github.com/leonardtng/cryptoscapes/issues/5)
4. [x] [TASK: Trending Coins Card](https://github.com/leonardtng/cryptoscapes/issues/12)
5. [x] [TASK: Global Data Card](https://github.com/leonardtng/cryptoscapes/issues/8)

Additional: [TASK: Top Institution Holders Card](https://github.com/leonardtng/cryptoscapes/issues/7)

**Additional context**
