### ISSUE TITLE
[EPIC] Trends Page

### ISSUE THREAD

**Issue by leonardtng** [leonardtng/cryptoscapes#9]
**Epic Details**
This feature will allow the user to track price correlation between coins using a heatmap.

**Describe the solution you'd like**
User can view the heatmap, and filter which coin data to appear as well as the date range of the data.

**List of Tasks (Complete in order)**
The tasks below can be completed in order (or not) to complete this feature.

1. [x] [TASK: Correlation Heatmap Chart](https://github.com/leonardtng/cryptoscapes/issues/10)
2. [x] [TASK: Fear and Greed Index Card](https://github.com/leonardtng/cryptoscapes/issues/14)
3. [x] [TASK: Market Sentiment Card](https://github.com/leonardtng/cryptoscapes/issues/15)

**Additional context**
